spring.application.name=FileManager

spring.datasource.url=jdbc:postgresql://localhost:5432/file-upload
spring.datasource.username=postgres
spring.datasource.password=########
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Maximum allowed size for a single uploaded file
spring.servlet.multipart.max-file-size=5MB
#Maximum total request size (useful for multi-file uploads)
spring.servlet.multipart.max-request-size=5MB

cloud.aws.credentials.access-key=##############
cloud.aws.credentials.secret-key=#################
cloud.aws.region.static= ########

aws.bucket.name=########

